name: Download MSMobAdSDK Pod

on:
  workflow_dispatch: # 允许手动运行

jobs:
  download-pod:
    runs-on: macos-latest

    steps:
      - name: 拉取代码仓库
        uses: actions/checkout@v4

      - name: 安装 CocoaPods
        run: sudo gem install cocoapods

      - name: 创建 Podfile
        run: |
          mkdir -p project
          cd project
          pod init
          echo "platform :ios, '12.0'" >> Podfile
          echo "target 'Dummy' do" >> Podfile
          echo "  pod 'MSMobAdSDK/MS','2.7.12.3'" >> Podfile
          echo "end" >> Podfile

      - name: 安装 Pod 依赖
        run: |
          cd project
          pod install --repo-update

      - name: 打包 Pods 目录
        run: |
          cd project
          zip -r ../MSMobAdSDK_Pods.zip Pods

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: MSMobAdSDK-Pods-Folder
          path: MSMobAdSDK_Pods.zip
          retention-days: 30
