name: Download MSMobAdSDK Pod

on:
  workflow_dispatch: # 允许手动触发

jobs:
  download-pod:
    runs-on: macos-latest

    steps:
      - name: 拉取代码仓库
        uses: actions/checkout@v4

      - name: 设置 CocoaPods 缓存
        id: cache-pods
        uses: actions/cache@v3
        with:
          path: ~/Library/Caches/CocoaPods/
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: 安装 CocoaPods
        run: sudo gem install cocoapods

      - name: 创建 Podfile
        run: |
          mkdir -p project
          cd project
          cat > Podfile << EOF
          platform :ios, '12.0'
          target 'Dummy' do
            pod 'MSMobAdSDK/MS','2.7.12.3'
          end
          EOF

      - name: 安装 Pod 依赖
        run: |
          cd project
          pod install --repo-update

      - name: 打包 Pods 目录
        run: |
          cd project
          zip -r ../MSMobAdSDK_Pods.zip Pods

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: MSMobAdSDK-Pods-Folder
          path: MSMobAdSDK_Pods.zip
          retention-days: 30
